### ISSUE TITLE
OpenMP errors when compiling latest release

### ISSUE THREAD

**Issue by MHBalsmeier** [earth-system-radiation/rte-rrtmgp#111]
Hi,

I get errors that I am unable to fix when compiling the latest release (v1.3). I am using CMake for the build process.
OS: Ubuntu 20.04
[CMakeLists.txt](https://github.com/AUN4GFD/game/blob/master/core/CMakeLists.txt)

error output: [output.txt](https://github.com/earth-system-radiation/rte-rrtmgp/files/6317192/output.txt)

Any idea what that is?

**Comment by RobertPincus** [comment]
@MHBalsmeier The project does not support CMake at this time. We are not in a position to debug every individual's setup. If the code itself has reproducible errors we would like to know and are grateful for pull requests that identify and fix them. 

That said, looking at your output suggests that you are trying to compile the code with Gnu Fortran 9,3 using OpenMP directives. The compilation failures arise when processing the OpenMP directives for for GPU offloading. It may be that the compiler does not support GPU offloading with OpenMP directives. If you don't plan to use a GPU there is no reason to build the code with OpenMP. 

Suggestions for compiler flags are available at https://github.com/earth-system-radiation/rte-rrtmgp/blob/main/Compiler-flags.md. If you have suggestions as to how these might be improved please open a pull request.

**Comment by MHBalsmeier** [comment]
Okay, thanks, sorry for asking, I will stick to the old version.

**Comment by RobertPincus** [comment]
@MHBalsmeier If you can convince CMake to compile without using OpenMP this should also work.

**Comment by MHBalsmeier** [comment]
Yes but my dynamical core is in C and I have OpenMP in it, it does not seem to be possible to compile the C code with OpenMP and RRTM without OpenMP. I can only compile the whole model with or without OpenMP.

**Comment by RobertPincus** [comment]
@MHBalsmeier You could consider to compile RTE+RRTMGP separately, with its own rules, and link to it as a library. This is an approach other models have taken. 

Likely CMake also allows you to specify compiler flags on a per-file or per-collection-of-files basis.

**Comment by MHBalsmeier** [comment]
Thanks, I'll try that.
