### ISSUE TITLE
gpt_Jac optional arguement code may be incorrect for OpenMP offload

### ISSUE THREAD

**Issue by naromero77** [earth-system-radiation/rte-rrtmgp#120]
As discussed in this PR https://github.com/earth-system-radiation/rte-rrtmgp/pull/117#discussion_r643431339

This style of OpenMP offload code may not be correct
https://github.com/earth-system-radiation/rte-rrtmgp/blob/main/rte/kernels-openacc/mo_rte_solver_kernels.F90#L203-L213

Even in the case of `do_Jacobians=False`, the OpenMP offload compiler may map variables which are not available on the CPU and lead to spurious seg. faults or other undefined behaviour. Note that most GPUs only have stack memory, so the variables are going to get allocated on the GPU even if the code is not executed  on the GPU. (I think, but not 100% sure)

There are times when seg. faults with the Cray OpenMP offload are encountered in the presence optional argument. It would be much better to examine alternate code structure to avoid these kernels as is proposed in the aforementioned PR.

**Comment by RobertPincus** [comment]
@naromero77 Thanks for bringing this up. It seems possible that we'll be expanding the use of logicals and dummy arguments in the kernels to manage optional arguments. 

Is there a way to verify that these code segments are causing the segmentation faults?

**Comment by RobertPincus** [comment]
As this does not seem to be a problem I am closing this issue, but I'll continue to be aware of the possibility.
