### ISSUE TITLE
Units in cloud optics extension?

### ISSUE THREAD

**Issue by peterukk** [earth-system-radiation/rte-rrtmgp#125]
Hi,

What are the units for cloud ice and liquid water paths, is it g/kg?  I would like to do all-sky computations using CAMS data. I noticed that the liquid water path I computed (from mixing ratios in kg/kg) had a maximum value of ~0.2 while the all-sky program fills the array with values of 0 or 10. The units should be written in mo_clouds_optics.F90.

**Comment by Chiil** [comment]
The paths are vertically integrated values over the dp of the grid cell and are treated in g/m2 in the cloud optics.

**Comment by peterukk** [comment]
G/m2, that's what I meant. Great, thanks

**Comment by RobertPincus** [comment]
Closed by d3956f7eaf9a9477076febf1609bf499b1a40e87
