### ISSUE TITLE
A flexible benchmarking program

### ISSUE THREAD

**Issue by RobertPincus** [earth-system-radiation/rte-rrtmgp#128]
For timing purposes it would be great to have a flexible benchmarking program. Timing estimates could build on @alexeedm's timing with `system_clock` in the all-sky example. 

We could use fixed concentrations for some greenhouse gases and analytic formulae for temperature, pressure, ozone, and water vapor, for example following the [RCEMIP](https://myweb.fsu.edu/awing/rcemip.html) protocol. Then we might want to vary: 
1. The number of columns tested
2. The number of columns done at a time
3. The number of levels
4. Clouds - yes or no? 

@alexeedm @Chiil Any additions or comments?

**Comment by Chiil** [comment]
That sounds like a good set. Maybe the set of gases (size and whether provided as constant, profile or field).

Ideally also the full set and a reduced set of gpoints (I test now with a 50 gpt set prepared by Menno as well).

**Comment by RobertPincus** [comment]
@Chiil Handling different-sized sets of g-points should come for free. 

Yes to being able to vary the number of gases used, at least between two extremes, but I'd put this at lower priority.

**Comment by RobertPincus** [comment]
`mo_rcemip_profiles.F90` now provides the ability to make profiles at arbitrary vertical resolution, so a program based on that could easily vary points 1, 2, and 3.
