### ISSUE TITLE
Small bug in mo_gas_optics_rrtmgp.F90

### ISSUE THREAD

**Issue by dustinswales** [earth-system-radiation/rte-rrtmgp#131]
I think there may be a small indexing error in the subroutine create_flavor() in mo_gas_optics_rrtmgp.F90.
https://github.com/earth-system-radiation/rte-rrtmgp/blob/main/rrtmgp/mo_gas_optics_rrtmgp.F90#L1558
To be consistent with the k-distribution data format, line 1558:
 do iatm=1,size(key_species,1)
should be replaced with:
 do iatm=1,size(key_species,2)

From the LW k-distribution file, key_species is ordered(pair, atmos_layer, bnd), [2,2,6]. Fortunately it has no impact since pair=atmos_layer.

**Comment by RobertPincus** [comment]
Thanks for finding this detail, @dustinswales 
Closed with 95865077bf63c3c93d4332a7be01ecac5ac729e9.
