### ISSUE TITLE
Potential indexing error rte/kernels-openacc/mo_rte_solver_kernels.F90

### ISSUE THREAD

**Issue by menzel-gfdl** [earth-system-radiation/rte-rrtmgp#140]
It looks like there is an indexing issue on this line:

https://github.com/earth-system-radiation/rte-rrtmgp/blob/3b5d157217fd97535a56b0a6810e7062e5d91fd4/rte/kernels-openacc/mo_rte_solver_kernels.F90#L1016

and maybe these lines too:

https://github.com/earth-system-radiation/rte-rrtmgp/blob/3b5d157217fd97535a56b0a6810e7062e5d91fd4/rte/kernels-openacc/mo_rte_solver_kernels.F90#L1018-L1022

Shouldn't `ngpt` be changed to `igpt`?

**Comment by RobertPincus** [comment]
@menzel-gfdl Right you are, thanks for the catch

**Comment by RobertPincus** [comment]
Closed by b2dd9f4.
