### ISSUE TITLE
Optimized compiler flags for PGI incorrect

### ISSUE THREAD

**Issue by goord** [earth-system-radiation/rte-rrtmgp#147]
The indicated compiler flags for PGI in `Compiler-flags.md` are intel-specific (i.e. identical to the intel flags). Using them in combination with nvfortran obviously breaks compilation.

**Comment by RobertPincus** [comment]
@goord Thanks for pointing this out. Do you have a set of flags that you would like to suggest?

**Comment by goord** [comment]
How about 
```
"-g -O3 -fast -Minfo -Mallocatable=03 -Mpreprocess"
```

**Comment by RobertPincus** [comment]
Closed with acb11e2
