### ISSUE TITLE
Generic names in C bindings

### ISSUE THREAD

**Issue by skosukhin** [earth-system-radiation/rte-rrtmgp#158]
Currently, certain subroutines are exposed via C bindings under very generic names, e.g. [`interpolation`](https://github.com/earth-system-radiation/rte-rrtmgp/blob/e9b7cbd70f286e6152e69f52c1a80018a13913b8/rrtmgp/kernels/mo_gas_optics_kernels.F90#L34). That might trigger a name collision in a user application.

A possible solution is to come up with some common prefix and use it for all public functions of the library, e.g. `rrtm_interpolation`.

**Comment by RobertPincus** [comment]
@skosukhin Thanks, this is a good idea. I'll try to implement in March some time.
