### ISSUE TITLE
Intel Compiler Optimization Problem on AMD EPYC ( Milan )

### ISSUE THREAD

**Issue by panosadamids-dkrz** [earth-system-radiation/rte-rrtmgp#159]
Problem: 
Intel compiler issues when building ICON with RTE-RRTMGP on "Levante", the new HPC system at DKRZ consisting of AMD EPYC Milan processors. The build using the Intel compiler is possible only if almost all optimizations are turned off. Especially the compiler options  -m64 -march=core-avx2 do not work at all.

The error occurs in the `subroutine interpolation` in file `rte-rrtmgp/rrtmgp/kernels/mo_gas_optics_kernels.F90` in the following nested loop:
<pre><code class="c">
eta = merge(col_gas(icol,ilay,igases(1)) / col_mix(itemp,icol,ilay,iflav), 0.5_wp, &
                        col_mix(itemp,icol,ilay,iflav) > 2._wp * tiny(col_mix))
loceta = eta * float(neta-1)
jeta(itemp,icol,ilay,iflav) = min(int(loceta)+1, neta-1)
</code></pre>

The result of the calculations for `jeta` is sometimes `jeta=-2147483647`, which leads to a segmentation fault.

Workarounds tried so far : 
1. suppress optimizations on the module `mo_gas_optics_kernels.F90` by using `!DIR$ NOOPTIMIZE` at the beginning of the module. It works but the performance degradation is unacceptable. 
2. replacing the declaration "REAL(wp), DIMENSION(2, ncol, nlay,nflav), INTENT(out) :: col_mix" with the assumed-shape variant "REAL(wp), DIMENSION(:,:,:,:), INTENT(out) :: col_mix".  This workaround works much better than the first one, but the performance is not as expected.

Next steps : 

1. trying the gcc compiler
2. try to reproduce the error with the stand alone tests of RTE-RRTMGP

**Comment by RobertPincus** [comment]
@panosadamids-dkrz I wonder if this is related to the problem found in single precision by @MennoVeerman (https://github.com/earth-system-radiation/rte-rrtmgp/pull/39#issuecomment-1044254604, #39)

Anyway I will be coming back to this code in the next few weeks.

**Comment by panosadamids-dkrz** [comment]
I could reproduce the above problem with the integrated stand alone RTE-RRTMGP tests.
The problem occurs when compiling with -O2 or -O3. 
Compile options -O0 and -O1 do work correctly.

**Comment by RobertPincus** [comment]
@panosadamids-dkrz Well, that's good news in the sense that we'll know when it's fixed. Can you explain to me how to compile the code in your setup on Levante, i.e. what modules to load and environment variables to set for the stand-alone tests?

**Comment by RobertPincus** [comment]
@panosadamids-dkrz As we changed the `merge` to an `if` in the recent change to the `develop` branch I would be curious to know if this issue has now been resolved.

**Comment by panosadamids-dkrz** [comment]
@RobertPincus I will check it !

**Comment by panosadamids-dkrz** [comment]
@RobertPincus :  This is issue has now been resolved. I have build the latest version on Levante  (AMD EPYC Milan) with high optimisation flag -O3, as mentioned above, and  the make, tests and check were successful.

**Comment by RobertPincus** [comment]
OK, so addressed by #223 and will close when moved to `main`

**Comment by skosukhin** [comment]
@RobertPincus if I am not mistaken, this particular issue was addressed in #170 and the workaround is still relevant, even with changes from #223.

**Comment by tlunttil** [comment]
It looks like workaround #170 is indeed needed even after replacing the `merge` with `if ... else`. Without it and using `-march=core-avx2` (which I guess it defaults to on Milan?), ifort seemed to generate the same code (a packed division and a blend) for both `merge` and `if` versions, so even with `if` there could potentially be a division by zero or other unpleasantries. It feels like a clear bug in the compiler.
