### ISSUE TITLE
Request for data files names to use ISO dates

### ISSUE THREAD

**Issue by m214089** [earth-system-radiation/rte-rrtmgp#160]
There are data files which do contain the generation date in their name. The older highres once have an ISO conforming datestring include, while the newer once with lower resolution refer to the time Augustus was leading the Roman Empire. Could that be changed to a proper date string?

**Comment by RobertPincus** [comment]
Data is moving to an external repo. Filenames will be static (no dates) and scheme data will be paired with reference data. Staged to `develop` as of [a6ccd35](https://github.com/earth-system-radiation/rte-rrtmgp/commit/a6ccd3510610ebc40efc8148345bd49896018ba1)

**Comment by RobertPincus** [comment]
See 3ac0636
