### ISSUE TITLE
Removing dtc/ccpp branch

### ISSUE THREAD

**Issue by RobertPincus** [earth-system-radiation/rte-rrtmgp#213]
Paging @SamuelTrahanNOAA @dustinswales: My understanding is that the implementation of RTE+RRTMGP has been consolidated in the UFS and that we are free to delete the dtc/ccpp branch. Any comments?

**Comment by SamuelTrahanNOAA** [comment]
You're asking the wrong person. I suggest you talk to @grantfirl

**Comment by dustinswales** [comment]
You can remove it.
(Robert, you need to get a birds field guide...)

**Comment by RobertPincus** [comment]
Sorry,  @pernak18 is the Orioles fan. 

Thanks y'all.
